---
title: "PS7: LASSO Regularization"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
```


## What's due when?

1. You have all by default been assigned to individual teams. However, you have the option do things in groups. This is an excellent opportunity to practice remote collaboration using a combination of Slack, GitHub, and Zoom. These are professional skills that I have found invaluable for my career.
    1. If you would like to be assigned to a team chosen by me, please let me know in a group Slack DM by **Saturday 5/4 9pm Eastern**.
    1. If you would like to work in self-chosen groups, please let me know in a group Slack DM by **Sunday 5/4 9pm Eastern** so that I can change your teams on GitHub.
1. By **Friday 4/10 9pm Eastern** (note evening due time) you must submit all your work on GitHub.


## Your work

In this problem set you will

1. Practice fitting LASSO models for
    1. Parameter shrinkage
    1. Variable selection
1. Get a jump on studying for Midterm II. Understanding LASSO and putting it in the context of common themes for all machine learning methods will form the bulk of Midterm II. As such, detailed solutions will be provided.


## Evaluation criteria


1. **"If others can't reproduce your work, they will throw it in the trash."** Submissions that don't knit will be penalized harshly. 
1. **"Presentation and communication-style matters."** Related to point above, for example
    + Plots: Keep the "ink-to-information" ratio in mind. Ensure your plots have labeled axes and informative titles.
    + Use markdown formatting to make your presentation effective.
    + Is code cleanly written, well-documented, and well-formatted. As the semester progresses, I'll be giving feedback from [The tidyverse style guide](https://style.tidyverse.org/).
1. After that, the evaluation criteria is iterative and cummulative in nature, reflecting the increasing difficulty of the questions. In other words, you do not need to complete the entire problem set to earn a "respectable" grade. For example, to earn 8/10 you only need to fit one LASSO model.
